[package]
name = "hello-rust"
version = "0.1.0"
authors = ["fj0lverkr <nils.nahooy@live.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ferris-says = "0.2"
rand = "0.6.0"
